name = "camaroom-cart-backend"
main = "src/index.js"
compatibility_date = "2024-11-01"

[vars]
MOMO_TRANSFER_NUMBER = "681105611"
MOMO_ACCOUNT_NAME = "su jiangmin"
ORDER_CURRENCY = "XAF"
MOMO_NETWORK_LABEL = "MTN Mobile Money or Orange Money"

[[d1_databases]]
binding = "DB"
database_name = "camaroom-orders"
database_id = "6b25460c-5248-4a1d-a5bf-c5abb23eda85"
