"""
Match the 2026-07-01 Cameroon price list to products in data/catalog_2026/
products.json (the shared source for assets/data/products.js) and patch the
matched entries' price:0 to their real FCFA price directly in products.js.

products.js is otherwise "generated by build_products.py — do not edit by
hand", but build_products.py has no price source at all (hardcodes price:0);
this script is a second, narrow pass that only ever touches the `price:0,`
token for matched SKUs, leaving everything else (including unmatched
products) untouched. Re-running build_products.py would wipe these prices —
re-run this script after any regeneration.

Same matching logic and rationale as rest-solar-agent's
scripts/apply_price_list.py (which prices the same catalog for the AI
chatbot's `products` SQL table): deliberately conservative, only prices a
SKU when its spec maps to exactly one price-list row with an unambiguous
price. 20% markup applied — this is the real Cameroon distributor's margin
protection (see docs/superpowers/plans/2026-07-20-manual-momo-payment.md),
so the website's cart price must match what the AI chatbot quotes.

Run: python3 scripts/apply_price_list.py [--dry-run]
"""
import argparse
import json
import re
from pathlib import Path

from openpyxl import load_workbook

REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOG_JSON = Path("/Users/lucasfeng/rest-solar-agent/data/catalog_2026/products.json")
SOURCE_XLSX = Path("/Users/lucasfeng/rest-solar-agent/data/price_list/restar_prices_cameroon_20260701_base.xlsx")
PRODUCTS_JS = REPO_ROOT / "assets" / "data" / "products.js"
MARKUP = 1.2


def parse_sheet():
    wb = load_workbook(SOURCE_XLSX, data_only=True)
    ws = wb.active
    top_category = None
    for row in ws.iter_rows(min_row=1, values_only=True):
        col1, col2 = row[1], row[2]
        if col1 is None:
            continue
        if col2 == "Model":
            top_category = str(col1).strip()
            continue
        if top_category is None:
            continue
        price = row[3]
        if not isinstance(price, (int, float)):
            continue
        spec = str(col2).strip() if col2 is not None else ""
        yield top_category, spec, round(price * MARKUP)


def _dims(s: str | None) -> tuple[int, ...] | None:
    if not s:
        return None
    nums = re.findall(r"\d+", s)
    return tuple(int(n) for n in nums[:3]) if len(nums) >= 3 else None


def _first_number(s: str | None) -> float | None:
    if not s:
        return None
    m = re.match(r"^\s*(\d+(?:\.\d+)?)\s*$", s)
    return float(m.group(1)) if m else None


def _voltage_tokens(s: str | None) -> set[str]:
    if not s:
        return set()
    return {t.strip() for t in re.split(r"[/,]", s) if t.strip()}


def build_dict(pairs: list[tuple], keyfn) -> dict:
    grouped: dict = {}
    for key_input, price in pairs:
        key = keyfn(key_input)
        if key is None:
            continue
        grouped.setdefault(key, set()).add(price)
    return {k: v.pop() for k, v in grouped.items() if len(v) == 1}


def match_panels(sheet_rows) -> dict[tuple, int]:
    pairs = [(spec, price) for cat, spec, price in sheet_rows if cat == "Solar panel"]
    return build_dict(pairs, _dims)


def match_gel_agm(sheet_rows, subcat: str) -> dict[tuple, int]:
    pairs = [(spec, price) for cat, spec, price in sheet_rows if cat == subcat]
    def keyfn(spec):
        m = re.match(r"^\s*([\d.]+V)\s*\*\s*([\d.]+)\s*AH", spec, re.I)
        return (m.group(1).upper(), float(m.group(2))) if m else None
    return build_dict(pairs, keyfn)


def match_lithium_kwh(sheet_rows) -> dict[float, int]:
    pairs = [(spec, price) for cat, spec, price in sheet_rows if cat == "Lithium Battery"]
    def keyfn(spec):
        m = re.search(r"([\d.]+)\s*KW\b", spec, re.I)
        return float(m.group(1)) if m else None
    return build_dict(pairs, keyfn)


def match_inverter_kw(sheet_rows) -> dict[float, int]:
    pairs = [(spec, price) for cat, spec, price in sheet_rows if cat == "Inverter"]
    def keyfn(spec):
        m = re.match(r"^\s*([\d.]+)\s*KW\s*$", spec, re.I)  # excludes "6.2KW Parallelable"
        return float(m.group(1)) if m else None
    return build_dict(pairs, keyfn)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    sheet_rows = list(parse_sheet())
    panel_prices = match_panels(sheet_rows)
    gel_prices = match_gel_agm(sheet_rows, "GEL battery")
    agm_prices = match_gel_agm(sheet_rows, "AGM battery")
    lithium_prices = match_lithium_kwh(sheet_rows)
    inverter_prices = match_inverter_kw(sheet_rows)

    raw_products = json.loads(CATALOG_JSON.read_text(encoding="utf-8"))

    updates: dict[str, tuple[int, str]] = {}  # sku -> (price, reason)
    for p in raw_products:
        sku = p["sku"]
        cat = p["category"]
        sub = p.get("subcategory") or ""
        price = None
        reason = ""
        if cat == "solar_panels":
            dims = _dims(p.get("dimensions"))
            if dims in panel_prices:
                price, reason = panel_prices[dims], f"dimensions {dims}"
        elif cat == "batteries" and sub == "GEL Battery":
            for vtok in _voltage_tokens(p.get("voltage")):
                ah = _first_number((p.get("capacity_ah") or "").replace("Ah", "").replace("AH", ""))
                key = (vtok.upper(), ah)
                if key in gel_prices:
                    price, reason = gel_prices[key], f"GEL {key}"
                    break
        elif cat == "batteries" and sub == "AGM Battery":
            for vtok in _voltage_tokens(p.get("voltage")):
                ah = _first_number((p.get("capacity_ah") or "").replace("Ah", "").replace("AH", ""))
                key = (vtok.upper(), ah)
                if key in agm_prices:
                    price, reason = agm_prices[key], f"AGM {key}"
                    break
        elif cat == "batteries" and sub == "LiFePO4 Battery":
            kwh = _first_number((p.get("capacity_kwh") or "").replace("kWh", "").replace("KWh", "").replace("KW", ""))
            if kwh in lithium_prices:
                price, reason = lithium_prices[kwh], f"Li {kwh}kWh"
        elif cat == "inverters":
            kw = _first_number((p.get("power_kw") or "").replace("kW", "").replace("KW", ""))
            if kw in inverter_prices:
                price, reason = inverter_prices[kw], f"Inverter {kw}kW"

        if price is not None:
            updates[sku] = (price, f"{sku} {p.get('model')!r} <- {reason}")

    print(f"Parsed {len(sheet_rows)} priced rows from {SOURCE_XLSX.name}.")
    print(f"Matched {len(updates)} of {len(raw_products)} products:\n")
    for sku, (price, reason) in updates.items():
        print(f"  {price:>8,} FCFA  {reason}")

    if args.dry_run:
        print("\n--dry-run: no changes written.")
        return

    js = PRODUCTS_JS.read_text(encoding="utf-8")
    applied = 0
    for sku, (price, _reason) in updates.items():
        pattern = re.compile(rf'(id:"{re.escape(sku)}"(?:(?!price:)[^}}])*?price:)0(,)')
        new_js, n = pattern.subn(rf"\g<1>{price}\g<2>", js)
        if n == 1:
            js = new_js
            applied += 1
        elif n == 0:
            print(f"  WARNING: could not find price:0 for {sku} in products.js")
        else:
            print(f"  WARNING: {sku} matched {n} times in products.js, skipped")

    PRODUCTS_JS.write_text(js, encoding="utf-8")
    print(f"\nApplied {applied} price updates to {PRODUCTS_JS}.")


if __name__ == "__main__":
    main()
